run:
  timeout: "1m"
  tests: true
  skip-dirs-use-default: true
  allow-parallel-runners: true
  go: "1.20"
linters:
  enable-all: true
  disable-all: false
  fast: true
  disable:
    - godox
linters-settings:
  funlen:
    lines: 70
    statements: 40
