version: "3.1"

services:
  db:
    image: postgres:15.2
    restart: always
    ports:
      - 5432:5432
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    env_file: ../.env
    hostname: postgres
    volumes:
      - ./_data/postgres/pgdata:/var/lib/postgresql/data/pgdata
