// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type City struct {
	ID          pgtype.UUID `db:"id" json:"id"`
	CountryCode string      `db:"country_code" json:"country_code"`
	Name        string      `db:"name" json:"name"`
	StateName   string      `db:"state_name" json:"state_name"`
}

type Country struct {
	Code string `db:"code" json:"code"`
	Name string `db:"name" json:"name"`
}

type Employee struct {
	ID           int32       `db:"id" json:"id"`
	Name         string      `db:"name" json:"name"`
	LastName     string      `db:"last_name" json:"last_name"`
	BirthDate    pgtype.Date `db:"birth_date" json:"birth_date"`
	EnterDate    pgtype.Date `db:"enter_date" json:"enter_date"`
	CreationDate pgtype.Date `db:"creation_date" json:"creation_date"`
	Gender       pgtype.Text `db:"gender" json:"gender"`
	PictureHash  pgtype.Text `db:"picture_hash" json:"picture_hash"`
}

type EmployeesLocation struct {
	EmployeeID int32       `db:"employee_id" json:"employee_id"`
	CityID     pgtype.UUID `db:"city_id" json:"city_id"`
	PostalCode pgtype.Text `db:"postal_code" json:"postal_code"`
}

type Team struct {
	ID     int32    `db:"id" json:"id"`
	Name   string   `db:"name" json:"name"`
	Topics []string `db:"topics" json:"topics"`
}

type TeamEmployee struct {
	EmployeeID int32 `db:"employee_id" json:"employee_id"`
	TeamID     int32 `db:"team_id" json:"team_id"`
}
