// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package sqlc

import (
	"context"
)

type Querier interface {
	AddEmployeeToTeam(ctx context.Context, arg AddEmployeeToTeamParams) error
	CreateEmployee(ctx context.Context, arg CreateEmployeeParams) (*Employee, error)
	CreateTeam(ctx context.Context, arg CreateTeamParams) (*Team, error)
	GetCities(ctx context.Context, limit int32) ([]*GetCitiesRow, error)
	GetCitiesByCountry(ctx context.Context, arg GetCitiesByCountryParams) ([]*GetCitiesByCountryRow, error)
	GetCountries(ctx context.Context) ([]*Country, error)
	GetEmployeeByID(ctx context.Context, id int32) (*Employee, error)
	UpdateEmployeeLocation(ctx context.Context, arg UpdateEmployeeLocationParams) error
}

var _ Querier = (*Queries)(nil)
